<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Mohammad Hussain Sutooda</Authors>
    <Description>Package Express shipping quote calculator assignment</Description>
  </PropertyGroup>

</Project>
